[06/28/2024 10:48:02] [e(0)] core: RuntimeError : Invalid template: com.dotgears.flappybird-1.3-4-minAPI8.apk
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:223:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/28/2024 10:49:25] [e(0)] core: RuntimeError : Invalid template: com.dotgears.flappybird-1.3-4-minAPI8.apk
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:223:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[11/04/2024 07:30:43] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[11/04/2024 07:30:43] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[11/04/2024 07:30:43] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[11/04/2024 07:30:56] [e(0)] core: Failed to open history file: /home/sumedh/.msf4/history with error: No such file or directory @ rb_sysopen - /home/sumedh/.msf4/history
[03/27/2025 22:36:53] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[03/27/2025 22:36:53] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[03/27/2025 22:36:53] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[03/27/2025 22:37:17] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:
/usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:165: SyntaxWarning: invalid escape sequence '\d'

[03/27/2025 22:37:17] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:
  versions = re.findall("(\d+\.\d+\.\d+)", banner)

[03/27/2025 22:37:40] [e(0)] core: Unable to load module /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go - SignalException SIGHUP
[05/19/2025 11:21:43] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[05/19/2025 11:21:43] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[05/19/2025 11:21:43] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[05/19/2025 11:21:54] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:
/usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:165: SyntaxWarning: invalid escape sequence '\d'

[05/19/2025 11:21:54] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/exploits/linux/smtp/haraka.py:
  versions = re.findall("(\d+\.\d+\.\d+)", banner)

[05/19/2025 11:36:49] [e(0)] core: Module exploit/linux/http/webmin_rpc_rce not found, and no loading errors found. If you're using a custom module refer to our wiki: https://docs.metasploit.com/docs/using-metasploit/intermediate/running-private-modules.html
[06/22/2025 13:34:02] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[06/22/2025 13:34:02] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[06/22/2025 13:34:02] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[06/22/2025 13:38:38] [e(0)] core: RuntimeError : Invalid template: /home/sumedh/Downloads/flappybird.apk
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:223:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/22/2025 13:42:16] [e(0)] core: RuntimeError : apktool version 2.7.0.pre.dirty not supported, please download at least version 2.9.2.
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:247:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/22/2025 13:46:13] [e(0)] core: RuntimeError : apksigner not found. If it's not in your PATH, please add it.
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:267:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/22/2025 13:48:33] [e(0)] core: RuntimeError : apksigner not found. If it's not in your PATH, please add it.
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:267:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/22/2025 13:49:34] [e(0)] core: RuntimeError : zipalign not found. If it's not in your PATH, please add it.
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:272:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:477:in `<main>'
[06/22/2025 14:08:12] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[06/22/2025 15:32:04] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[06/22/2025 15:36:15] [w(0)] core: Session 1 has died
[06/22/2025 15:36:32] [w(0)] core: Session 2 has died
[06/22/2025 15:36:44] [d(0)] core: Session 1 failed to negotiate TLV encryption
[06/22/2025 15:36:57] [d(0)] core: Session 2 failed to negotiate TLV encryption
[06/22/2025 15:38:13] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[06/22/2025 15:41:16] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/09/2025 18:48:03] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[07/09/2025 18:48:03] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[07/09/2025 18:48:03] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[07/09/2025 19:19:17] [i(0)] core: Trying to continue despite failed database creation: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[07/09/2025 19:19:17] [e(0)] core: DB.connect threw an exception - ActiveRecord::ConnectionNotEstablished connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[07/09/2025 19:19:17] [e(0)] core: Failed to connect to the database: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

